### ISSUE TITLE
Slides show blank screen

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#14]
Pressing s for slideshow opens window, which prompts for webcam access,  but entire window is blank.

**Comment by whilei** [comment]
Serving over http? Pressing s from where? Emacs? Any messages in the browser's console?

**Comment by whilei** [comment]
Note that if an issue like this disrupts your workflow, you can reset your working directory to how it was before a merge with: 

```
git checkout 765hs3 # the commit hash from the last commit before the merge
git branch -b time-machine
```
and later use a `rebase` to place your following time-machine commits back onto the upstream once the issue is addressed.

**Comment by webappzero** [comment]
Thanks for the git checkout tip! This isn't a big disruption for my writing process at all. Please don't burn any midnight oil.

Normal behavior is: after opening notes.html, pressing `s` key in browser window displaying presentation will open a separate window with speakers notes. This window usually has 3 panes: present slide, next slide preview, and notes.

 Maybe this was caused by SALT folder?

Here's screenshot of the console messages.

http://img.webappzero.com/iuxi

**Comment by whilei** [comment]
I can reproduce by refreshing the browser with the notes window once open, but it works for me otherwise. If the problem persists let's schedule a quick video meeting to step through it.  I've attached two screenshots; the first of a functioning notes-window, and the second of a post-refresh-notes-window. 

![screen shot 2017-01-27 at 10 40 10](https://cloud.githubusercontent.com/assets/10228550/22366597/d5a2196a-e47d-11e6-9578-f47fb5d3ff33.png)
![screen shot 2017-01-27 at 10 40 35](https://cloud.githubusercontent.com/assets/10228550/22366598/d5d0858e-e47d-11e6-8063-b436a460aea0.png)

**Comment by webappzero** [comment]
Mine is working now too. Refresh does blank screen too, but we don't need to worry about this. Goosechase complete, hopefully ; )
