### ISSUE TITLE
leverage live ui reload via node

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#16]
What do you think about this idea?

We could copy the contents of the reveal.js folder into the project root, rename `notes.org` to `index.org` and delete the `test` dir in project root (its not used).

This would allow us to export index.org to index.html as normal, but any such change, and also changes in css or js, would trigger hot reload of the ui.

In addition to the obvious development & design workflow improvement, this brings node back into the picture, which will allow us to leverage its rich eco system for our final week and half of creativity.

Any possible downsides?

**Comment by whilei** [comment]
The only downside I see is that it creates an interdependence of concerns; which is to say it makes it makes the project "a reveal.js project", instead of "a project incorporating reveal.js". But I don't see too many negative or complicated implications of that move aside from swapping a couple paths.

I think it's worth going for, since aside from your content, Reveal is integral to the life-force of presentation, so it makes sense to keep the concerns closely linked. Would do it (as usual) on a branch in case un-foreseens rear up. Shall I go for it?

**Comment by webappzero** [comment]
Go for it : )

I'm clean now this is a good time.
