### ISSUE TITLE
QR Polling

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#34]
This looks like a good candidate for a polling solution.

http://directpoll.com

**Comment by whilei** [comment]
DirectPoll looks good. I assume you'd like to use your own/company's email to register (or set up an email for this project). Can you please send me a login for whichever route you'd like to go with? I'll get started prototyping and building polls as they come up.

**Comment by webappzero** [comment]
One problem I see with Direct Poll is that we have to "save" the poll every 30 days to keep it from being removed.

If we want to keep the idea of polling in the talk, I'm wondering if we could just generate our own QR code to something like google forms or survey, something that would be sharable to the public so they can see the data. Preferably free.

**Comment by webappzero** [comment]
This might kick start some ideas for us:
https://trevorfox.com/2015/09/qr-codes-scan-to-vote-app-ifttt-google-sheets/

**Comment by whilei** [comment]
Yep, awesome resource. 

Here's our first working QR poll Google Docs Spreadsheet! 
https://docs.google.com/spreadsheets/d/1mhx786wMi-_Htng_7T3nTyr5ZJLU7WnpIBwDDYf4dqc/edit?usp=sharing

... made by visiting https://maker.ifttt.com/trigger/CR17-VoL/with/key/BwlFonVF1hd-SW0gYKrMk?value1=hello&value2=testing&value3=hola via QR code or otherwise

**Comment by whilei** [comment]
❗️ It's also worth noting that this kind of polling is limited to A/B multiple-choice, and each choice requires its own QR code. 

That means we'll need multiple QRs for anything requiring more than a single-value answer, ie `Scan if you like learning` needs only one code (and doesn't provide _really_ interesting results), while `Do you like learning or muffins more?` requires 2 QRs, and so forth.

**Comment by whilei** [comment]
Another approach would be to use a single QR to point to https://docs.google.com/forms.

📝 eg https://goo.gl/forms/leE8fYUa0M1yLGxb2 <-- I'm inclined to this one for ease of use, and we can open the polling data with a [linked spreadsheet](https://docs.google.com/spreadsheets/d/1tdxUHeLVq4ogVDVULLe3mB8FuJuiHsvy6Xxca7c3CbU/edit?usp=sharing)

~~__Or__ we could even embed the form right in the presentation, ala `<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScUgaxwwpCyuXRsKvL2GFK19nTiGPoWQlR3-_JhppFnEOiSIA/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>`~~

🙃 __Update__: Can't embed a live form in a video.

**Comment by webappzero** [comment]
I like the single QR code pointing to a form. Great find!

**Comment by whilei** [comment]
Watching the rehearsal currently! 

What would you think about modifying (oh no! not again!) the redpill :pill: to include a reference to that pill's action. 

Since the redpill+QR serves ~~three~~ four[^1] functions, it may be helpful to offer a reminder/visual que of what you'd be getting yourself into when you scan. 

Something of a compromise between earlier options.

I drew up some prototypes...
![red-pill-link](https://cloud.githubusercontent.com/assets/10228550/22626669/812d7b9e-ebb3-11e6-8153-240911849b4f.png)
![red-pill-octocat](https://cloud.githubusercontent.com/assets/10228550/22626670/816b2dcc-ebb3-11e6-9192-10aabbfbd560.png)
![red-pill-twitter](https://cloud.githubusercontent.com/assets/10228550/22626671/817195ea-ebb3-11e6-917d-a9fac7e4c7a6.png)

[^1]: Website, tweet, Github, form.

**Comment by webappzero** [comment]
Fantastic idea!

I'd like to flatten the design as much as possible while still honoring their respective brand rules. E.g. for github we could use this (from https://github.com/logos): 

http://img.webappzero.com/j2Kq

And from twitter we could use  a white bird: http://img.webappzero.com/j2TR from here: https://brand.twitter.com/he.html

and use a white link to match these. The github will have some black in it, but so does the QR code. That will keep our colors front and center.

Awesome idea!

**Comment by whilei** [comment]
See images (1a5c935) and changes to use those images in index.org (a932c06).

**Comment by webappzero** [comment]
What if we use a white version of this, instead of the green google forms logo, to keep our color scheme more consistent?

Attribution required in a bibliography section

http://www.flaticon.com/free-icon/google-forms_104090

**Comment by whilei** [comment]
Yep we're on the same lines, I should have referenced a later commit https://github.com/webappzero/the-value-of-learning/commit/999a31ee980eee947a3bee9c0895c0e86eb2f0f6, which includes a white pencil. Will slate in the official Form logo instead.

**Comment by webappzero** [comment]
I like your pencil better. It's more semantic for user input, and less general. The form logo could also look like a page. Thanks!
