### ISSUE TITLE
notes-text.html broken

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#55]
Pressing `t` opens a new blank tab with no address in address bar, but not speaker notes as usual.

Can you spot any commits that might have affected this?

**Comment by webappzero** [comment]
Please don't stay up late on this. It can wait until the morning.

**Comment by whilei** [comment]
I don't see any recent commits that have changed `notes-text.html`. 

One thing I notice is that, as a side-effect of the javascript listener methods that Reveal/+Reveal-Notes use, the popopen window for `notes-text.html` won't "refresh" along with `index.html`; it instead becomes 'orphaned'. So if you're using live-reload and make a change to `index.html` and your browser reloads, the already-open text window will essentially become useless. 

The obvious workaround for that that works for me is to close the orphaned text window and just hit `t` again after a refresh.

Otherwise, I can't replicate the issue on my side. Let me know if it persists for you.

**Comment by webappzero** [comment]
Doh! Issue was only on my machine.

I use a chrome extension called 'context' to manage my extensions. I had inadvertently set it to the wrong profile, and had an extension conflict. I embarassed I didn't consider my local settings. 

Thank you for investigating nonetheless, and I'm glad you mentioned the issue with refresh. That's good to know!
