### ISSUE TITLE
Github Pages for static hosting.

### ISSUE THREAD

**Issue by whilei** [webappzero/cr17-to-zero#6]
Would be cool! At least for hosting the show statically. 

Still looking into the implications of using the __multiplexer__ (ba ba ba bummmm) along with Pages as far as authentication control for things like changing slides, but it might be doable.

And just wanted to get us going on using Issues (maybe?!) to keep track of TODOs, would-be-cool-features, and whatever else comes up.

**Comment by webappzero** [comment]
Yes, very cool. I have thevalueoflearning.org and valueoflearning.org that we can use.

Yes on Github issues. Great suggestion!

We can think about getting the fonts to work from a CDN, so that the talk will look the same for everyone.

We should also think of a strategy for the video feed box (white box). Will it not be used on the slides? Or could we take a bunch of screen shots from the video, after the talk, and include photos of me to make it like I'm talking. Heavier for mobile users to download all those pics, but kinda neat.

**Comment by webappzero** [comment]
Going to close this for now. We can reopen in a couple months.
