### ISSUE TITLE
frag causes scroll down, but not on fresh start

### ISSUE THREAD

**Issue by webappzero** [webappzero/cr17-to-zero#63]
Hi Isaac,

Frag causes scroll down by 2 lines, but only after I've looked at a few slides and then backed up. 

I said in video to only work on this for one hour, but it is important, so there's not a budget constraint on hours. You can manage it yourself against your other tasks is what I meant. Please this whole 5 min video to see exactly what I mean and hear a work around I suggest:

https://youtu.be/KVbP7BDk-Csk

: )

**Comment by whilei** [comment]
Gotcha, hmm... 

I can't reproduce it on my end ☹️, punching through many slides and returning to frag- and notes-heavy slides to find a window jumper. 

The states look like they _should_ be properly ignoring anything that's not a full slide change.

__Possible clues / Questions to double check:__
- Most web browsers use `SPC` and `[arrow-down]` to shift the window position down as a default. It's possible your Chrome is misbehaving when it should be passing those keystrokes on to Reveal's JS. 
- Does it happen in Safari?
- Are you using `SPC` and `DEL` to move between frags+slides, or arrow keys?
- Does the same thing happen if you have the main window focused instead of the text window?
- Does it happen if you resize the text window to be bigger (but still short enough to need scrolling)?

If the problem persists I'll go ahead and see if I can dig anything up in the JS. (I would love to avoid a text-based workaround that would distract/muddle the text content of your talk 🤕)

**Comment by webappzero** [comment]
Perfect sleuthing Isaac. You got me on the scent!

I found this help doc: http://superuser.com/questions/192647/stop-chrome-from-scrolling-down-every-time-i-hit-space

searched for and installed this chrome extension:

https://github.com/mikecrittenden/chrome-shortkeys

Created a shortcut which set `space` to `do nothing` and now I'm retired on the beach, living the dream.

**Comment by whilei** [comment]
Marvelous. 🍾
