### ISSUE TITLE
Crowdcast.io login for Isaac

### ISSUE THREAD

**Issue by whilei** [webappzero/cr17-to-zero#86]

**Comment by webappzero** [comment]
https://www.crowdcast.io/e/tvol-rehearsal/register

**Comment by webappzero** [comment]
After reconsidering, I think its best if you activate a free trial, create a crowdcast event at quarter after our mtg starts, and invite me as a participant. Then you will upgrade me to presenter, but only when we meet tomorrow.

According to Ryan just now, Crowdcast records the feed themselves, along with time-based event/chat information & analytics in the sessions

Attendees can replay sessions after the fact like they were attending them live

 (within about 5-10 minutes of the session ending)

So we should be able to replicate an ideal, worst-case scenario, since you are 'across the pond'.

**Comment by whilei** [comment]
https://www.crowdcast.io/e/fake-cr17

![screen shot 2017-02-07 at 19 56 35](https://cloud.githubusercontent.com/assets/10228550/22706462/a1a2dbfe-ed6f-11e6-9766-b87608fe8cea.png)

**Comment by webappzero** [comment]
Interesting. I'll take a stab in the dark. Maybe they're using webrtc, and you're using Safari?

Looks like Safari isn't very webrtc friendly yet.

 http://caniuse.com/#search=webrtc

**Comment by whilei** [comment]
Yep! It's a Safari thing. Works fine on Chrome! 👍 

And it looks like, as you said, I'll have to invite you to the screen pretty much on the spot (can't invite you to collaborate now).

**Comment by whilei** [comment]
> Send them to [ccst.io/e/fake-cr17](Send them to ccst.io/e/fake-cr17)
